name: Bug report
description: Report reproducible incorrect behavior
title: 'bug: '
labels: [bug]
body:
  - type: textarea
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
    validations:
      required: true
  - type: input
    attributes:
      label: Pukbot version
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
    validations:
      required: true
